apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::122955132264:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18HI2NWGNV4VH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::122955132264:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-09T13:19:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "914"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 071801a8-f2af-4523-b4ef-a71bc663052f
